### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by panuravolainen** [Cbyte-training-org/caption-this#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by panuravolainen** [comment]
Hi

**Comment by tgauthier-exp** [comment]
Hi

**Comment by JohnBiname** [comment]
This is not a comment

**Comment by romain-koenig** [comment]
\o/

**Comment by selimfek** [comment]
Hello 🖐🏻

**Comment by laurentbel** [comment]
Ola !

**Comment by tonyfrpr** [comment]
👍

**Comment by charly-maillefaud** [comment]
Hey team ! ✌️

**Comment by MuzammeelAuhammud-work** [comment]
hello

**Comment by camillemartinon** [comment]
Hi

**Comment by ronhanson** [comment]
Hello team
